// number theory

// LEVEL - 1

// 1. PRIMALITY TEST
// 2. SEIVE OF ERATOSTHENES
// 3. PRIME NO IN A INTERVAL
// 4. FINDING PRIME PRIME 
// 5. FINDING PRIME FACTOR
// 6. FINDING PRIME FACTOR USING SEIVE
// 7. BINARY EXPONENTIATION
// 8. MATRIX EXPONENTIATION
// 9. EUCLID GCD

